OUTPUT= libUCL
OBJ= SystemEnvironment.o FileSystem.o CTokenizer.o CFile.o CThread.o CSerialPort.o CUnixDomainSocket.o

include ../../DevEnv/sharedLibSettings

FileSystem.o:	FileSystem.cpp FileSystem.h
CTokenizer.o:	CTokenizer.cpp CTokenizer.h
CFile.o:	CFile.h CFile.cpp
CThread.o:	CThread.h CThread.cpp
SystemEnvironment.o: SystemEnvironment.cpp SystemEnvironment.h
CSerialPort.o:	CSerialPort.cpp CSerialPort.h
CUnixDomainSocket.o:	CUnixDomainSocket.h CUnixDomainSocket.cpp
