OUTPUT= rbcgateway
OBJ= CRBCGateway.o

include ../../DevEnv/executableSettings

LFLAGS+= -lControllerInterface -lTTSInterface -lJoystickInterface -lRuntime -lUCL -lLogger

CRBCGateway.o	: CRBCGateway.cpp CRBCGateway.h
