#!/bin/bash 

export CC=$1
export PROJECT_ROOT=$2
export TOOLCHAIN_LIB_PATHS=""

export PROJECT_BIN_PATH=$PROJECT_ROOT/Bin
export TARGET_PATH=$PROJECT_BIN_PATH/Target
export INTERMEDIATE_PATH=$PROJECT_BIN_PATH/Intermediate
export TARGET_SHARED_LIBS_PATH=$TARGET_PATH/usr/lib
export TARGET_BIN_PATH=$TARGET_PATH/bin
export TARGET_WWW_PATH=$TARGET_PATH/srv/www
export THIRD_PARTY_COMPONENTS=$PROJECT_ROOT/3rdParty
export DEPLOYMENT_SCRIPTS=$PROJECT_ROOT/DeploymentScripts
export DEPLOYMENT_SETTINGS=$DEPLOYMENT_SCRIPTS/deploymentPaths
export SYSTEM_CONFIGURATION_DIRECTORY=$DEPLOYMENT_SCRIPTS/ConfigurationFiles

#preparing the filenames and paths for the makefile common settings
export MAKEFILE_RULES=$PROJECT_ROOT/DevEnv
export COMMON_MAKE_SETTINGS=$MAKEFILE_RULES/commonSettings
#preparing the filenames and paths for deployment scripts

# generate the common makefile 
echo "export CC:=$CC" >> $COMMON_MAKE_SETTINGS
echo "export ARCHIVER:=ar" >> $COMMON_MAKE_SETTINGS
echo "export BIN_PATH:=$PROJECT_ROOT/Bin" >> $COMMON_MAKE_SETTINGS
echo "export INTERMEDIATE_PATH=$INTERMEDIATE_PATH" >> $COMMON_MAKE_SETTINGS
echo "export TARGET_PATH=$TARGET_PATH" >> $COMMON_MAKE_SETTINGS
echo "export SHARED_LIB_PATH=$TARGET_SHARED_LIBS_PATH" >> $COMMON_MAKE_SETTINGS
echo "export CFLAGS:= -c -Wall -pedantic -I\"$PROJECT_ROOT/Src/Global\" -I\"$PROJECT_ROOT/Src\"" >> $COMMON_MAKE_SETTINGS
echo "export LFLAGS:= -pthread -L$INTERMEDIATE_PATH -L$TARGET_SHARED_LIBS_PATH" >> $COMMON_MAKE_SETTINGS
