OUTPUT= libLogger
OBJ= CLogManager.o CLogMsg.o CLoggingAgent.o CConsoleTarget.o

include ../../DevEnv/sharedLibSettings

CLogManager.o:	CLogManager.cpp CLogManager.h 
CLogMsg.o: CLogMsg.cpp CLogMsg.h
CLoggingAgent.o: CLoggingAgent.cpp CLoggingAgent.h
CConsoleTarget.o: CConsoleTarget.cpp CConsoleTarget.h
