OUTPUT=test_UCL
OBJ=CTest_SerialPort.o CSerialPort.o CTest_Tokenizer.o CTokenizer.o
VPATH=$(SUBJ_PATH)/UCL

include ../../DevEnv/unitTestSettings

CSerialPort.o:	CSerialPort.cpp CSerialPort.h
CTokenizer.o:	CTokenizer.cpp CTokenizer.h
CTest_SerialPort.o:	CTest_SerialPort.cpp
CTEST_Tokenizer.o:	CTest_Tokenizer.cpp