#!/bin/bash
source deploymentPaths
echo "Creating root directory for target filesystem on: "$TARGET_PATH
mkdir -p $TARGET_PATH

echo "Creating basic directory structure"
mkdir -p $TARGET_PATH/dev
mkdir -p $TARGET_PATH/dev/pts
mkdir -p $TARGET_PATH/etc
mkdir -p $TARGET_PATH/etc/init.d
mkdir -p $TARGET_PATH/proc
mkdir -p $TARGET_PATH/sys
mkdir -p $TARGET_PATH/root
mkdir -p $TARGET_PATH/bin
mkdir -p $TARGET_PATH/lib
mkdir -p $TARGET_PATH/srv
mkdir -p $TARGET_PATH/srv/www
mkdir -p $TARGET_PATH/srv/www/cgi-bin

echo "creating device files"
mknod $TARGET_PATH/dev/console c 5 1
mknod $TARGET_PATH/dev/null c 1 3

