#!/bin/bash
source deploymentPaths

#copy generic configurations
cp -r $SYSTEM_CONFIGURATION_DIRECTORY/Common/* $TARGET_PATH

#platform specific files
if [ $BUILD_PLATFORM = "QEMU" ]; then
	echo "Copying the Configuration files for QEMU"
	cp -r $SYSTEM_CONFIGURATION_DIRECTORY/qemu_cfg/* $TARGET_PATH
elif [ $BUILD_PLATFORM = "KRISTECH" ]; then
	echo "Copying the Configuration files for KRISTECH"
	cp -r $SYSTEM_CONFIGURATION_DIRECTORY/kristech_cfg/* $TARGET_PATH
else
	echo Other deployment configurations are not distinguished
fi
