#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts devpts /dev/pts
mount -t tmpfs none dev/shm

echo "lnxdev" > /proc/sys/kernel/hostname

/sbin/mdev -s
ifconfig eth0 10.0.2.15
