#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts devpts /dev/pts
mount -t tmpfs none dev/shm

echo "lnxdev" > /proc/sys/kernel/hostname

echo configure the www server
ln /bin/cgiprocessor /srv/www/cgi-bin/controller
httpd -h /srv/www

/sbin/mdev -s
ifconfig eth0 10.0.2.15
