#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts devpts /dev/pts

echo "lnxdev" > /proc/kernel/hostname

/sbin/mdev -s
ifconfig eth0 192.168.0.75
route add default gw 192.168.0.1
