OUTPUT= libConfiguration
OBJ= CConfiguration.o CConfigNode.o CParameter.o

include ../../DevEnv/sharedLibSettings

LFLAGS+= -lXMLParser -lUCL


CConfiguration.o: CConfiguration.cpp CConfiguration.h
CConfigNode.o: CConfigNode.cpp CConfigNode.h
CParameter.o: CParameter.cpp CParameter.h
