OUTPUT= newTest
OBJ= CNewProcess.o CConfiguration.o CConfigNode.o

include ../../DevEnv/executableSettings

CNewProcess.o:	CNewProcess.cpp CNewProcess.h
CConfiguration.o: CConfiguration.cpp CConfiguration.h
CConfigNode.o: CConfigNode.cpp CConfigNode.h
