OUTPUT= exampleApp
OBJ= CExampleApp.o

include ../../DevEnv/executableSettings

LFLAGS+= -lControllerInterface -lTTSInterface -lJoystickInterface -lRuntime -lUCL -lLogger

CExampleApp.o	: CExampleApp.cpp CExampleApp.h
