OUTPUT= libControllerInterface
OBJ = CControllerProxy.o CControllerStub.o

include ../../DevEnv/staticLibSettings

CControllerProxy.o: CControllerProxy.cpp CControllerProxy.h
CControllerStub.o: CControllerStub.cpp CControllerStub.h

