/* gSOAP_DS_Stub.h
   Generated by gSOAP 2.8.17r from DataService.soapHeader

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef gSOAP_DS_Stub_H
#define gSOAP_DS_Stub_H
#include <vector>
#include "stdsoap2.h"
#if GSOAP_VERSION != 20817
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ds2__GetServiceStatusResponse
#define SOAP_TYPE_ds2__GetServiceStatusResponse (10)
/* ds2:GetServiceStatusResponse */
struct ds2__GetServiceStatusResponse
{
public:
	int return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
public:
	int soap_type() const { return 10; } /* = unique type id SOAP_TYPE_ds2__GetServiceStatusResponse */
};
#endif

#ifndef SOAP_TYPE_ds2__GetServiceStatus
#define SOAP_TYPE_ds2__GetServiceStatus (11)
/* ds2:GetServiceStatus */
struct ds2__GetServiceStatus
{
public:
	int soap_type() const { return 11; } /* = unique type id SOAP_TYPE_ds2__GetServiceStatus */
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ds2__TrackDataResponse
#define SOAP_TYPE_ds2__TrackDataResponse (14)
/* ds2:TrackDataResponse */
struct ds2__TrackDataResponse
{
public:
	int _return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:int */
public:
	int soap_type() const { return 14; } /* = unique type id SOAP_TYPE_ds2__TrackDataResponse */
};
#endif

#ifndef SOAP_TYPE_ds2__TrackData
#define SOAP_TYPE_ds2__TrackData (15)
/* ds2:TrackData */
struct ds2__TrackData
{
public:
	std::string _trackItems;	/* required element of type xsd:string */
public:
	int soap_type() const { return 15; } /* = unique type id SOAP_TYPE_ds2__TrackData */
};
#endif

#ifndef SOAP_TYPE_ds2__ExecuteCommandResponse
#define SOAP_TYPE_ds2__ExecuteCommandResponse (18)
/* ds2:ExecuteCommandResponse */
struct ds2__ExecuteCommandResponse
{
public:
	std::string _return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
public:
	int soap_type() const { return 18; } /* = unique type id SOAP_TYPE_ds2__ExecuteCommandResponse */
};
#endif

#ifndef SOAP_TYPE_ds2__ExecuteCommand
#define SOAP_TYPE_ds2__ExecuteCommand (19)
/* ds2:ExecuteCommand */
struct ds2__ExecuteCommand
{
public:
	std::string _commandName;	/* required element of type xsd:string */
	std::string _arguments;	/* required element of type xsd:string */
public:
	int soap_type() const { return 19; } /* = unique type id SOAP_TYPE_ds2__ExecuteCommand */
};
#endif

#ifndef SOAP_TYPE_ds2__GetDataResponse
#define SOAP_TYPE_ds2__GetDataResponse (21)
/* ds2:GetDataResponse */
struct ds2__GetDataResponse
{
public:
	std::string _return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
public:
	int soap_type() const { return 21; } /* = unique type id SOAP_TYPE_ds2__GetDataResponse */
};
#endif

#ifndef SOAP_TYPE_ds2__GetData
#define SOAP_TYPE_ds2__GetData (22)
/* ds2:GetData */
struct ds2__GetData
{
public:
	std::string _itemName;	/* required element of type xsd:string */
public:
	int soap_type() const { return 22; } /* = unique type id SOAP_TYPE_ds2__GetData */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (23)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 23; } /* = unique type id SOAP_TYPE_SOAP_ENV__Header */
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (24)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 24; } /* = unique type id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (26)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 26; } /* = unique type id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (29)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 29; } /* = unique type id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (30)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 30; } /* = unique type id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of gSOAP_DS_Stub.h */
