/* gSOAP_DS_H.h
   Generated by gSOAP 2.8.17r from DataService.soapHeader

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef gSOAP_DS_H_H
#define gSOAP_DS_H_H
#include "gSOAP_DS_Stub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 gSOAP_DS__instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 gSOAP_DS__fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 gSOAP_DS__container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_std__string(soap, data),0) || soap_put_std__string(soap, data, "string", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);

inline std::string * soap_new_std__string(struct soap *soap, int n = -1) { return soap_instantiate_std__string(soap, n, NULL, NULL, NULL); }

inline std::string * soap_new_req_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline std::string * soap_new_set_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline void soap_delete_std__string(struct soap *soap, std::string *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ds2__GetData
#define SOAP_TYPE_ds2__GetData (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ds2__GetData(struct soap*, struct ds2__GetData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ds2__GetData(struct soap*, const struct ds2__GetData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ds2__GetData(struct soap*, const char*, int, const struct ds2__GetData *, const char*);
SOAP_FMAC3 struct ds2__GetData * SOAP_FMAC4 soap_in_ds2__GetData(struct soap*, const char*, struct ds2__GetData *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ds2__GetData(struct soap*, const struct ds2__GetData *, const char*, const char*);

#ifndef soap_write_ds2__GetData
#define soap_write_ds2__GetData(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ds2__GetData(soap, data),0) || soap_put_ds2__GetData(soap, data, "ds2:GetData", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ds2__GetData * SOAP_FMAC4 soap_get_ds2__GetData(struct soap*, struct ds2__GetData *, const char*, const char*);

#ifndef soap_read_ds2__GetData
#define soap_read_ds2__GetData(soap, data) ( soap_begin_recv(soap) || !soap_get_ds2__GetData(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ds2__GetData * SOAP_FMAC2 soap_instantiate_ds2__GetData(struct soap*, int, const char*, const char*, size_t*);

inline struct ds2__GetData * soap_new_ds2__GetData(struct soap *soap, int n = -1) { return soap_instantiate_ds2__GetData(soap, n, NULL, NULL, NULL); }

inline struct ds2__GetData * soap_new_req_ds2__GetData(struct soap *soap, std::string& _itemName) { struct ds2__GetData *_p = soap_instantiate_ds2__GetData(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__GetData(soap, _p); _p->_itemName = _itemName; } return _p; }

inline struct ds2__GetData * soap_new_set_ds2__GetData(struct soap *soap, std::string& _itemName) { struct ds2__GetData *_p = soap_instantiate_ds2__GetData(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__GetData(soap, _p); _p->_itemName = _itemName; } return _p; }

inline void soap_delete_ds2__GetData(struct soap *soap, struct ds2__GetData *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ds2__GetData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ds2__GetDataResponse
#define SOAP_TYPE_ds2__GetDataResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ds2__GetDataResponse(struct soap*, struct ds2__GetDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ds2__GetDataResponse(struct soap*, const struct ds2__GetDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ds2__GetDataResponse(struct soap*, const char*, int, const struct ds2__GetDataResponse *, const char*);
SOAP_FMAC3 struct ds2__GetDataResponse * SOAP_FMAC4 soap_in_ds2__GetDataResponse(struct soap*, const char*, struct ds2__GetDataResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ds2__GetDataResponse(struct soap*, const struct ds2__GetDataResponse *, const char*, const char*);

#ifndef soap_write_ds2__GetDataResponse
#define soap_write_ds2__GetDataResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ds2__GetDataResponse(soap, data),0) || soap_put_ds2__GetDataResponse(soap, data, "ds2:GetDataResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ds2__GetDataResponse * SOAP_FMAC4 soap_get_ds2__GetDataResponse(struct soap*, struct ds2__GetDataResponse *, const char*, const char*);

#ifndef soap_read_ds2__GetDataResponse
#define soap_read_ds2__GetDataResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ds2__GetDataResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ds2__GetDataResponse * SOAP_FMAC2 soap_instantiate_ds2__GetDataResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ds2__GetDataResponse * soap_new_ds2__GetDataResponse(struct soap *soap, int n = -1) { return soap_instantiate_ds2__GetDataResponse(soap, n, NULL, NULL, NULL); }

inline struct ds2__GetDataResponse * soap_new_req_ds2__GetDataResponse(struct soap *soap, std::string& _return_) { struct ds2__GetDataResponse *_p = soap_instantiate_ds2__GetDataResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__GetDataResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline struct ds2__GetDataResponse * soap_new_set_ds2__GetDataResponse(struct soap *soap, std::string& _return_) { struct ds2__GetDataResponse *_p = soap_instantiate_ds2__GetDataResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__GetDataResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline void soap_delete_ds2__GetDataResponse(struct soap *soap, struct ds2__GetDataResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ds2__GetDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ds2__ExecuteCommand
#define SOAP_TYPE_ds2__ExecuteCommand (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ds2__ExecuteCommand(struct soap*, struct ds2__ExecuteCommand *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ds2__ExecuteCommand(struct soap*, const struct ds2__ExecuteCommand *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ds2__ExecuteCommand(struct soap*, const char*, int, const struct ds2__ExecuteCommand *, const char*);
SOAP_FMAC3 struct ds2__ExecuteCommand * SOAP_FMAC4 soap_in_ds2__ExecuteCommand(struct soap*, const char*, struct ds2__ExecuteCommand *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ds2__ExecuteCommand(struct soap*, const struct ds2__ExecuteCommand *, const char*, const char*);

#ifndef soap_write_ds2__ExecuteCommand
#define soap_write_ds2__ExecuteCommand(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ds2__ExecuteCommand(soap, data),0) || soap_put_ds2__ExecuteCommand(soap, data, "ds2:ExecuteCommand", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ds2__ExecuteCommand * SOAP_FMAC4 soap_get_ds2__ExecuteCommand(struct soap*, struct ds2__ExecuteCommand *, const char*, const char*);

#ifndef soap_read_ds2__ExecuteCommand
#define soap_read_ds2__ExecuteCommand(soap, data) ( soap_begin_recv(soap) || !soap_get_ds2__ExecuteCommand(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ds2__ExecuteCommand * SOAP_FMAC2 soap_instantiate_ds2__ExecuteCommand(struct soap*, int, const char*, const char*, size_t*);

inline struct ds2__ExecuteCommand * soap_new_ds2__ExecuteCommand(struct soap *soap, int n = -1) { return soap_instantiate_ds2__ExecuteCommand(soap, n, NULL, NULL, NULL); }

inline struct ds2__ExecuteCommand * soap_new_req_ds2__ExecuteCommand(struct soap *soap, std::string& _commandName, std::string& _arguments) { struct ds2__ExecuteCommand *_p = soap_instantiate_ds2__ExecuteCommand(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__ExecuteCommand(soap, _p); _p->_commandName = _commandName; _p->_arguments = _arguments; } return _p; }

inline struct ds2__ExecuteCommand * soap_new_set_ds2__ExecuteCommand(struct soap *soap, std::string& _commandName, std::string& _arguments) { struct ds2__ExecuteCommand *_p = soap_instantiate_ds2__ExecuteCommand(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__ExecuteCommand(soap, _p); _p->_commandName = _commandName; _p->_arguments = _arguments; } return _p; }

inline void soap_delete_ds2__ExecuteCommand(struct soap *soap, struct ds2__ExecuteCommand *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ds2__ExecuteCommand(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ds2__ExecuteCommandResponse
#define SOAP_TYPE_ds2__ExecuteCommandResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ds2__ExecuteCommandResponse(struct soap*, struct ds2__ExecuteCommandResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ds2__ExecuteCommandResponse(struct soap*, const struct ds2__ExecuteCommandResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ds2__ExecuteCommandResponse(struct soap*, const char*, int, const struct ds2__ExecuteCommandResponse *, const char*);
SOAP_FMAC3 struct ds2__ExecuteCommandResponse * SOAP_FMAC4 soap_in_ds2__ExecuteCommandResponse(struct soap*, const char*, struct ds2__ExecuteCommandResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ds2__ExecuteCommandResponse(struct soap*, const struct ds2__ExecuteCommandResponse *, const char*, const char*);

#ifndef soap_write_ds2__ExecuteCommandResponse
#define soap_write_ds2__ExecuteCommandResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ds2__ExecuteCommandResponse(soap, data),0) || soap_put_ds2__ExecuteCommandResponse(soap, data, "ds2:ExecuteCommandResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ds2__ExecuteCommandResponse * SOAP_FMAC4 soap_get_ds2__ExecuteCommandResponse(struct soap*, struct ds2__ExecuteCommandResponse *, const char*, const char*);

#ifndef soap_read_ds2__ExecuteCommandResponse
#define soap_read_ds2__ExecuteCommandResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ds2__ExecuteCommandResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ds2__ExecuteCommandResponse * SOAP_FMAC2 soap_instantiate_ds2__ExecuteCommandResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ds2__ExecuteCommandResponse * soap_new_ds2__ExecuteCommandResponse(struct soap *soap, int n = -1) { return soap_instantiate_ds2__ExecuteCommandResponse(soap, n, NULL, NULL, NULL); }

inline struct ds2__ExecuteCommandResponse * soap_new_req_ds2__ExecuteCommandResponse(struct soap *soap, std::string& _return_) { struct ds2__ExecuteCommandResponse *_p = soap_instantiate_ds2__ExecuteCommandResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__ExecuteCommandResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline struct ds2__ExecuteCommandResponse * soap_new_set_ds2__ExecuteCommandResponse(struct soap *soap, std::string& _return_) { struct ds2__ExecuteCommandResponse *_p = soap_instantiate_ds2__ExecuteCommandResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__ExecuteCommandResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline void soap_delete_ds2__ExecuteCommandResponse(struct soap *soap, struct ds2__ExecuteCommandResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ds2__ExecuteCommandResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ds2__TrackData
#define SOAP_TYPE_ds2__TrackData (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ds2__TrackData(struct soap*, struct ds2__TrackData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ds2__TrackData(struct soap*, const struct ds2__TrackData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ds2__TrackData(struct soap*, const char*, int, const struct ds2__TrackData *, const char*);
SOAP_FMAC3 struct ds2__TrackData * SOAP_FMAC4 soap_in_ds2__TrackData(struct soap*, const char*, struct ds2__TrackData *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ds2__TrackData(struct soap*, const struct ds2__TrackData *, const char*, const char*);

#ifndef soap_write_ds2__TrackData
#define soap_write_ds2__TrackData(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ds2__TrackData(soap, data),0) || soap_put_ds2__TrackData(soap, data, "ds2:TrackData", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ds2__TrackData * SOAP_FMAC4 soap_get_ds2__TrackData(struct soap*, struct ds2__TrackData *, const char*, const char*);

#ifndef soap_read_ds2__TrackData
#define soap_read_ds2__TrackData(soap, data) ( soap_begin_recv(soap) || !soap_get_ds2__TrackData(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ds2__TrackData * SOAP_FMAC2 soap_instantiate_ds2__TrackData(struct soap*, int, const char*, const char*, size_t*);

inline struct ds2__TrackData * soap_new_ds2__TrackData(struct soap *soap, int n = -1) { return soap_instantiate_ds2__TrackData(soap, n, NULL, NULL, NULL); }

inline struct ds2__TrackData * soap_new_req_ds2__TrackData(struct soap *soap, std::string& _trackItems) { struct ds2__TrackData *_p = soap_instantiate_ds2__TrackData(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__TrackData(soap, _p); _p->_trackItems = _trackItems; } return _p; }

inline struct ds2__TrackData * soap_new_set_ds2__TrackData(struct soap *soap, std::string& _trackItems) { struct ds2__TrackData *_p = soap_instantiate_ds2__TrackData(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__TrackData(soap, _p); _p->_trackItems = _trackItems; } return _p; }

inline void soap_delete_ds2__TrackData(struct soap *soap, struct ds2__TrackData *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ds2__TrackData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ds2__TrackDataResponse
#define SOAP_TYPE_ds2__TrackDataResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ds2__TrackDataResponse(struct soap*, struct ds2__TrackDataResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ds2__TrackDataResponse(struct soap*, const struct ds2__TrackDataResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ds2__TrackDataResponse(struct soap*, const char*, int, const struct ds2__TrackDataResponse *, const char*);
SOAP_FMAC3 struct ds2__TrackDataResponse * SOAP_FMAC4 soap_in_ds2__TrackDataResponse(struct soap*, const char*, struct ds2__TrackDataResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ds2__TrackDataResponse(struct soap*, const struct ds2__TrackDataResponse *, const char*, const char*);

#ifndef soap_write_ds2__TrackDataResponse
#define soap_write_ds2__TrackDataResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ds2__TrackDataResponse(soap, data),0) || soap_put_ds2__TrackDataResponse(soap, data, "ds2:TrackDataResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ds2__TrackDataResponse * SOAP_FMAC4 soap_get_ds2__TrackDataResponse(struct soap*, struct ds2__TrackDataResponse *, const char*, const char*);

#ifndef soap_read_ds2__TrackDataResponse
#define soap_read_ds2__TrackDataResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ds2__TrackDataResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ds2__TrackDataResponse * SOAP_FMAC2 soap_instantiate_ds2__TrackDataResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ds2__TrackDataResponse * soap_new_ds2__TrackDataResponse(struct soap *soap, int n = -1) { return soap_instantiate_ds2__TrackDataResponse(soap, n, NULL, NULL, NULL); }

inline struct ds2__TrackDataResponse * soap_new_req_ds2__TrackDataResponse(struct soap *soap, int _return_) { struct ds2__TrackDataResponse *_p = soap_instantiate_ds2__TrackDataResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__TrackDataResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline struct ds2__TrackDataResponse * soap_new_set_ds2__TrackDataResponse(struct soap *soap, int _return_) { struct ds2__TrackDataResponse *_p = soap_instantiate_ds2__TrackDataResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__TrackDataResponse(soap, _p); _p->_return_ = _return_; } return _p; }

inline void soap_delete_ds2__TrackDataResponse(struct soap *soap, struct ds2__TrackDataResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ds2__TrackDataResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ds2__GetServiceStatus
#define SOAP_TYPE_ds2__GetServiceStatus (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ds2__GetServiceStatus(struct soap*, struct ds2__GetServiceStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ds2__GetServiceStatus(struct soap*, const struct ds2__GetServiceStatus *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ds2__GetServiceStatus(struct soap*, const char*, int, const struct ds2__GetServiceStatus *, const char*);
SOAP_FMAC3 struct ds2__GetServiceStatus * SOAP_FMAC4 soap_in_ds2__GetServiceStatus(struct soap*, const char*, struct ds2__GetServiceStatus *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ds2__GetServiceStatus(struct soap*, const struct ds2__GetServiceStatus *, const char*, const char*);

#ifndef soap_write_ds2__GetServiceStatus
#define soap_write_ds2__GetServiceStatus(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ds2__GetServiceStatus(soap, data),0) || soap_put_ds2__GetServiceStatus(soap, data, "ds2:GetServiceStatus", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ds2__GetServiceStatus * SOAP_FMAC4 soap_get_ds2__GetServiceStatus(struct soap*, struct ds2__GetServiceStatus *, const char*, const char*);

#ifndef soap_read_ds2__GetServiceStatus
#define soap_read_ds2__GetServiceStatus(soap, data) ( soap_begin_recv(soap) || !soap_get_ds2__GetServiceStatus(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ds2__GetServiceStatus * SOAP_FMAC2 soap_instantiate_ds2__GetServiceStatus(struct soap*, int, const char*, const char*, size_t*);

inline struct ds2__GetServiceStatus * soap_new_ds2__GetServiceStatus(struct soap *soap, int n = -1) { return soap_instantiate_ds2__GetServiceStatus(soap, n, NULL, NULL, NULL); }

inline struct ds2__GetServiceStatus * soap_new_req_ds2__GetServiceStatus(struct soap *soap) { struct ds2__GetServiceStatus *_p = soap_instantiate_ds2__GetServiceStatus(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__GetServiceStatus(soap, _p); } return _p; }

inline struct ds2__GetServiceStatus * soap_new_set_ds2__GetServiceStatus(struct soap *soap) { struct ds2__GetServiceStatus *_p = soap_instantiate_ds2__GetServiceStatus(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__GetServiceStatus(soap, _p); } return _p; }

inline void soap_delete_ds2__GetServiceStatus(struct soap *soap, struct ds2__GetServiceStatus *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ds2__GetServiceStatus(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ds2__GetServiceStatusResponse
#define SOAP_TYPE_ds2__GetServiceStatusResponse (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ds2__GetServiceStatusResponse(struct soap*, struct ds2__GetServiceStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ds2__GetServiceStatusResponse(struct soap*, const struct ds2__GetServiceStatusResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ds2__GetServiceStatusResponse(struct soap*, const char*, int, const struct ds2__GetServiceStatusResponse *, const char*);
SOAP_FMAC3 struct ds2__GetServiceStatusResponse * SOAP_FMAC4 soap_in_ds2__GetServiceStatusResponse(struct soap*, const char*, struct ds2__GetServiceStatusResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ds2__GetServiceStatusResponse(struct soap*, const struct ds2__GetServiceStatusResponse *, const char*, const char*);

#ifndef soap_write_ds2__GetServiceStatusResponse
#define soap_write_ds2__GetServiceStatusResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ds2__GetServiceStatusResponse(soap, data),0) || soap_put_ds2__GetServiceStatusResponse(soap, data, "ds2:GetServiceStatusResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ds2__GetServiceStatusResponse * SOAP_FMAC4 soap_get_ds2__GetServiceStatusResponse(struct soap*, struct ds2__GetServiceStatusResponse *, const char*, const char*);

#ifndef soap_read_ds2__GetServiceStatusResponse
#define soap_read_ds2__GetServiceStatusResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ds2__GetServiceStatusResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct ds2__GetServiceStatusResponse * SOAP_FMAC2 soap_instantiate_ds2__GetServiceStatusResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ds2__GetServiceStatusResponse * soap_new_ds2__GetServiceStatusResponse(struct soap *soap, int n = -1) { return soap_instantiate_ds2__GetServiceStatusResponse(soap, n, NULL, NULL, NULL); }

inline struct ds2__GetServiceStatusResponse * soap_new_req_ds2__GetServiceStatusResponse(struct soap *soap, int return_) { struct ds2__GetServiceStatusResponse *_p = soap_instantiate_ds2__GetServiceStatusResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__GetServiceStatusResponse(soap, _p); _p->return_ = return_; } return _p; }

inline struct ds2__GetServiceStatusResponse * soap_new_set_ds2__GetServiceStatusResponse(struct soap *soap, int return_) { struct ds2__GetServiceStatusResponse *_p = soap_instantiate_ds2__GetServiceStatusResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ds2__GetServiceStatusResponse(soap, _p); _p->return_ = return_; } return _p; }

inline void soap_delete_ds2__GetServiceStatusResponse(struct soap *soap, struct ds2__GetServiceStatusResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ds2__GetServiceStatusResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

/* End of gSOAP_DS_H.h */
